openapi: 3.0.0
info:
  title: Moodi-pie API
  description: 스웨거 API
  version: v1.0.0
servers:
- url: https://moodipie.duckdns.org
- url: https://운영URL
tags:
- name: 음악 CRUD
  description: 스포티파이에서 가져온 음악정보
- name: 플레이리스트 CRUD
  description: 플레이리스트 CRUD
- name: 스포티파이 api
  description: 스포티파이 외부 api
- name: 회원
  description: 회원관리 CRUD
paths:
  /api/users:
    get:
      tags:
      - 회원
      summary: 마이페이지 조회
      description: 내 정보를 조회합니다.
      operationId: userPage
      responses:
        "200":
          description: "이름 : 김무디, 프로필 사진 : moody"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ApiResUserInfoResponse"
        "400":
          description: 요청 실패
          content:
            application/json:
              examples:
                조회 실패 - userEmail 오류:
                  summary: ""
                  description: userEmail 값이 Null 이라서 플레이리스트 조회에 실패했습니다.
                  value:
                    httpStatus: 400
                    message: NULL 값이 존재합니다.
                    divisionCode: G003
      security:
      - Authorization: []
    put:
      tags:
      - 회원
      summary: 내 정보 수정
      description: 내 정보를 수정합니다.
      operationId: updateUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateUserRequest"
        required: true
      responses:
        "200":
          description: 수정 성공
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ApiResUserInfoResponse"
        "400":
          description: 요청 실패
          content:
            application/json:
              examples:
                수정 실패 - 필드 에러:
                  summary: ""
                  description: 필드 조건에 맞지 않아 회원정보 수정에 실패했습니다.
                  value:
                    httpStatus: 400
                    message: 잘못된 형식입니다.
                    divisionCode: G002
      security:
      - Authorization: []
    delete:
      tags:
      - 회원
      summary: 회원 탈퇴
      description: 회원 탈퇴합니다.
      operationId: deleteUser
      responses:
        "200":
          description: 탈퇴 성공
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ApiResUserInfoResponse"
        "400":
          description: 요청 실패
          content:
            application/json:
              examples:
                조회 실패 - userEmail 오류:
                  summary: ""
                  description: userEmail 값이 Null 이라서 플레이리스트 조회에 실패했습니다.
                  value:
                    httpStatus: 400
                    message: NULL 값이 존재합니다.
                    divisionCode: G003
      security:
      - Authorization: []
  /api/playlists/{playlistNumber}:
    get:
      tags:
      - 플레이리스트 CRUD
      summary: 플레이리스트 정보 조회
      description: 생성된 플레이리스트를 조회합니다.
      operationId: playlistResponse
      parameters:
      - name: playlistNumber
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: 조회 성공
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ApiResPlaylistTrackResponse"
        "400":
          description: 요청 실패
          content:
            application/json:
              examples:
                조회 실패 - playlistNumber NULL:
                  summary: ""
                  description: 잘못된 playlistNumber로 조회하여 플레이리스트 조회에 실패했습니다.
                  value:
                    httpStatus: 400
                    message: NULL 값이 존재합니다.
                    divisionCode: G003
      security:
      - Authorization: []
    put:
      tags:
      - 플레이리스트 CRUD
      summary: 플레이리스트 정보 수정
      description: 생성된 플레이리스트를 수정합니다.
      operationId: updatePlaylist
      parameters:
      - name: playlistNumber
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdatePlaylistRequest"
        required: true
      responses:
        "200":
          description: 수정 성공
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ApiResUpdatePlaylistRequest"
        "400":
          description: 요청 실패
          content:
            application/json:
              examples:
                수정 실패 - playlistNumber NULL:
                  summary: ""
                  description: 잘못된 playlistNumber로 수정을 시도하여 플레이리스트 수정에 실패했습니다.
                  value:
                    httpStatus: 400
                    message: NULL 값이 존재합니다.
                    divisionCode: G003
                수정 실패 - 필드 에러:
                  summary: ""
                  description: 필드 조건에 맞지 않아 플레이리스트 수정에 실패했습니다.
                  value:
                    httpStatus: 400
                    message: 잘못된 형식입니다.
                    divisionCode: G002
      security:
      - Authorization: []
    delete:
      tags:
      - 플레이리스트 CRUD
      summary: 플레이리스트 삭제
      description: 홈 화면에서 플레이리스트를 삭제합니다.
      operationId: deletePlaylist
      parameters:
      - name: playlistNumber
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: 삭제 성공
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ApiResPlaylistResponse"
        "400":
          description: 요청 실패
          content:
            application/json:
              examples:
                삭제 실패 - playlistNumber NULL:
                  summary: ""
                  description: 잘못된 playlistNumber 로 삭제를 시도하여 플레이리스트 삭제에 실패했습니다.
                  value:
                    httpStatus: 400
                    message: NULL 값이 존재합니다.
                    divisionCode: G003
      security:
      - Authorization: []
  /api/token:
    post:
      tags:
      - 회원
      summary: 토큰 갱신
      description: 만료될 토큰을 갱신합니다.
      operationId: refreshToken
      parameters:
      - name: Authorization
        in: header
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: 토큰 갱신 성공
          content:
            '*/*':
              schema:
                type: string
        "400":
          description: BAD_REQUEST
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ApiRes"
      security:
      - Authorization: []
  /api/spotify/api/tracks:
    post:
      tags:
      - 스포티파이 api
      summary: 외부 api로 노래 저장
      description: 노래를 가져와 db에 저장합니다.
      operationId: saveTracks
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/SpotifyTrackRequest"
        required: true
      responses:
        "200":
          description: 저장 성공
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ApiResListCreateTrackRequest"
        "400":
          description: 요청 실패
          content:
            application/json:
              examples:
                저장 실패- trackId NULL:
                  summary: ""
                  description: 잘못된 TrackId로 조회를 시도하여 트랙 조회에 실패했습니다.
                  value:
                    httpStatus: 400
                    message: NULL 값이 존재합니다.
                    divisionCode: G003
        "404":
          description: 리소스를 찾을 수 없음
          content:
            application/json:
              examples:
                생성 실패 - 스포티파이 오류:
                  summary: ""
                  description: 스포티파이 오류로 플레이리스트가 생성되지 않았습니다.
                  value:
                    httpStatus: 404
                    message: 스포티파이에서 곡을 찾지 못했습니다.
                    divisionCode: S001
      security:
      - Authorization: []
  /api/signup:
    post:
      tags:
      - 회원
      summary: 회원가입
      description: 회원에 가입합니다.
      operationId: signup
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateUserRequest"
        required: true
      responses:
        "201":
          description: 회원가입 성공
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ApiResCreateUserRequest"
        "400":
          description: 요청 실패
          content:
            application/json:
              examples:
                회원가입 실패 - 필드 에러:
                  summary: ""
                  description: 필드 조건에 맞지 않아 회원가입에 실패했습니다.
                  value:
                    httpStatus: 400
                    message: 잘못된 형식입니다.
                    divisionCode: G002
  /api/playlists:
    get:
      tags:
      - 플레이리스트 CRUD
      summary: 홈에서 플레이리스트 조회
      description: 홈 화면에서 플레이리스트를 조회합니다.
      operationId: findAllPlaylist
      responses:
        "200":
          description: 조회 성공
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ApiResListPlaylistResponse"
        "400":
          description: 요청 실패
          content:
            application/json:
              examples:
                조회 실패 - userEmail 오류:
                  summary: ""
                  description: userEmail 값이 Null 이라서 플레이리스트 조회에 실패했습니다.
                  value:
                    httpStatus: 400
                    message: NULL 값이 존재합니다.
                    divisionCode: G003
      security:
      - Authorization: []
    post:
      tags:
      - 플레이리스트 CRUD
      summary: 플레이리스트 생성
      description: 새로운 플레이리스트를 생성합니다.
      operationId: savePlaylist
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreatePlaylistRequest"
        required: true
      responses:
        "201":
          description: 생성 성공
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ApiResPlaylistResponse"
        "400":
          description: 요청 실패
          content:
            application/json:
              examples:
                생성 실패 - 플레이리스트 NULL:
                  summary: ""
                  description: 요청값이 없어 플레이리스트가 생성되지 않았습니다.
                  value:
                    httpStatus: 400
                    message: 잘못된 형식입니다.
                    divisionCode: G002
        "404":
          description: 리소스를 찾을 수 없음
          content:
            application/json:
              examples:
                생성 실패 - 스포티파이 오류:
                  summary: ""
                  description: 스포티파이 오류로 플레이리스트가 생성되지 않았습니다.
                  value:
                    httpStatus: 404
                    message: 스포티파이에서 곡을 찾지 못했습니다.
                    divisionCode: S001
      security:
      - Authorization: []
  /api/logout:
    post:
      tags:
      - 회원
      summary: 로그아웃
      description: 로그아웃합니다.
      operationId: logout
      responses:
        "200":
          description: 로그아웃 성공
          content:
            '*/*':
              schema:
                type: string
        "400":
          description: BAD_REQUEST
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ApiRes"
      security:
      - Authorization: []
  /api/login:
    post:
      tags:
      - 회원
      summary: 로그인
      description: 내 정보로 로그인합니다.
      operationId: login
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserLoginRequest"
        required: true
      responses:
        "200":
          description: 로그인 성공
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/UserLoginResponse"
        "400":
          description: BAD_REQUEST
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ApiRes"
  /api/tracks/{trackId}:
    get:
      tags:
      - 음악 CRUD
      summary: 음악조회
      description: 가져온 음악을 조회합니다.
      operationId: getTrack
      parameters:
      - name: trackId
        in: path
        description: 트랙 정보 얻기 위한 트랙 아이디
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: 조회 성공
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ApiResTrackResponse"
        "400":
          description: 요청 실패
          content:
            application/json:
              examples:
                조회 실패- trackId NULL:
                  summary: ""
                  description: 잘못된 TrackId로 조회를 시도하여 트랙 조회에 실패했습니다.
                  value:
                    httpStatus: 400
                    message: NULL 값이 존재합니다.
                    divisionCode: G003
      security:
      - Authorization: []
  /api/playlists/{playlistNumber}/tracks/{playlistTrackNumber}:
    delete:
      tags:
      - 플레이리스트 CRUD
      summary: 플레이리스트 내부 트랙 삭제
      description: 플레이리스트 내부의 트랙을 삭제 합니다.
      operationId: deletePlaylistTrack
      parameters:
      - name: playlistNumber
        in: path
        description: 선택할 플레이리스트 아이디
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      - name: playlistTrackNumber
        in: path
        description: 삭제할 트랙 번호
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: 삭제 성공
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ApiResPlaylistTrackEachResponse"
        "400":
          description: 요청 실패
          content:
            application/json:
              examples:
                삭제 실패 - playlistNumber or trackId NULL:
                  summary: ""
                  description: 잘못된 playlistNumber 나 TrackId로 삭제를 시도하여 플레이리스트 삭제에 실패했습니다.
                  value:
                    httpStatus: 400
                    message: NULL 값이 존재합니다.
                    divisionCode: G003
      security:
      - Authorization: []
components:
  schemas:
    ApiRes:
      title: API 응답
      type: object
      properties:
        httpStatus:
          type: integer
          description: 응답코드
          format: int32
        data:
          type: object
          description: 응답 데이터
        message:
          type: string
          description: 응답 메세지
          example: ex.조회에 성공했습니다.
        divisionCode:
          type: string
          description: 오류 구분 코드
          example: 오류시 출력
        errors:
          type: array
          description: 상세 필드 에러
          example: 오류시 출력
          items:
            $ref: "#/components/schemas/FieldErrors"
    FieldErrors:
      type: object
      properties:
        field:
          type: string
        value:
          type: string
        reason:
          type: string
    UpdateUserRequest:
      required:
      - username
      type: object
      properties:
        username:
          type: string
          description: 수정된 이름
          example: 둘리(공백X)
    ApiResUserInfoResponse:
      title: API 응답
      type: object
      properties:
        httpStatus:
          type: integer
          description: 응답코드
          format: int32
        data:
          $ref: "#/components/schemas/UserInfoResponse"
        message:
          type: string
          description: 응답 메세지
          example: ex.조회에 성공했습니다.
        divisionCode:
          type: string
          description: 오류 구분 코드
          example: 오류시 출력
        errors:
          type: array
          description: 상세 필드 에러
          example: 오류시 출력
          items:
            $ref: "#/components/schemas/FieldErrors"
    UserInfoResponse:
      type: object
      properties:
        username:
          type: string
          description: 이름
          example: 홍길동
        email:
          type: string
          description: 이메일
          example: moodipie@gmail.com
    UpdatePlaylistRequest:
      required:
      - emotion
      - playlistImage
      - title
      type: object
      properties:
        title:
          type: string
          description: 플레이리스트 제목
          example: 우울할때 듣는 음악
        playlistImage:
          type: string
          description: 플레이리스트 이미지 URL
          example: http://dfdfjiweoif.com
        emotion:
          type: string
          description: 감정
          example: SAD
          enum:
          - HAPPY
          - SAD
          - MAD
          - EXCITING
          - TIRED
    ApiResUpdatePlaylistRequest:
      title: API 응답
      type: object
      properties:
        httpStatus:
          type: integer
          description: 응답코드
          format: int32
        data:
          $ref: "#/components/schemas/UpdatePlaylistRequest"
        message:
          type: string
          description: 응답 메세지
          example: ex.조회에 성공했습니다.
        divisionCode:
          type: string
          description: 오류 구분 코드
          example: 오류시 출력
        errors:
          type: array
          description: 상세 필드 에러
          example: 오류시 출력
          items:
            $ref: "#/components/schemas/FieldErrors"
    SpotifyTrackRequest:
      required:
      - artistName
      - trackName
      type: object
      properties:
        trackName:
          type: string
          description: 트랙 제목
          example: 바다의 왕자
        artistName:
          type: string
          description: 가수이름
          example: 박명수
    ApiResListCreateTrackRequest:
      title: API 응답
      type: object
      properties:
        httpStatus:
          type: integer
          description: 응답코드
          format: int32
        data:
          type: array
          description: 응답 데이터
          items:
            $ref: "#/components/schemas/CreateTrackRequest"
        message:
          type: string
          description: 응답 메세지
          example: ex.조회에 성공했습니다.
        divisionCode:
          type: string
          description: 오류 구분 코드
          example: 오류시 출력
        errors:
          type: array
          description: 상세 필드 에러
          example: 오류시 출력
          items:
            $ref: "#/components/schemas/FieldErrors"
    CreateTrackRequest:
      required:
      - artistName
      - imageUrl
      - trackId
      - trackName
      type: object
      properties:
        trackId:
          type: string
          description: 트랙 ID
          example: sdakfjiosdwn1dnfsd
        trackName:
          type: string
          description: 트랙 제목
          example: 바다의 왕자
        artistName:
          type: string
          description: 가수이름
          example: 박명수
        imageUrl:
          type: string
          description: 이미지 URL
          example: http://dfdfjiweoif.com
    CreateUserRequest:
      required:
      - email
      - password
      - username
      type: object
      properties:
        username:
          type: string
          description: 이름
          example: 홍길동
        email:
          type: string
          description: 이메일
          example: moodipie@gmail.com
        password:
          maxLength: 2147483647
          minLength: 8
          type: string
          description: password
          example: teamproject1!
    ApiResCreateUserRequest:
      title: API 응답
      type: object
      properties:
        httpStatus:
          type: integer
          description: 응답코드
          format: int32
        data:
          $ref: "#/components/schemas/CreateUserRequest"
        message:
          type: string
          description: 응답 메세지
          example: ex.조회에 성공했습니다.
        divisionCode:
          type: string
          description: 오류 구분 코드
          example: 오류시 출력
        errors:
          type: array
          description: 상세 필드 에러
          example: 오류시 출력
          items:
            $ref: "#/components/schemas/FieldErrors"
    CreatePlaylistRequest:
      required:
      - emotion
      - playlistImage
      - title
      - trackIds
      type: object
      properties:
        title:
          type: string
          description: 플레이리스트 제목
          example: 우울할때 듣는 음악
        playlistImage:
          type: string
          description: 플레이리스트 이미지 URL
          example: http://dfdfjiweoif.com
        emotion:
          type: string
          description: 감정
          example: SAD
          enum:
          - HAPPY
          - SAD
          - MAD
          - EXCITING
          - TIRED
        trackIds:
          type: array
          description: 플레이리스트 트랙 ID들
          example:
          - 7ouMYWpwJ422jRcDASZB7P
          - 4VqPOruhp5EdPBeR92t6lQ
          - 2takcwOaAZWiXQijPHIx7B
          items:
            type: string
    ApiResPlaylistResponse:
      title: API 응답
      type: object
      properties:
        httpStatus:
          type: integer
          description: 응답코드
          format: int32
        data:
          $ref: "#/components/schemas/PlaylistResponse"
        message:
          type: string
          description: 응답 메세지
          example: ex.조회에 성공했습니다.
        divisionCode:
          type: string
          description: 오류 구분 코드
          example: 오류시 출력
        errors:
          type: array
          description: 상세 필드 에러
          example: 오류시 출력
          items:
            $ref: "#/components/schemas/FieldErrors"
    PlaylistResponse:
      type: object
      properties:
        playlistNumber:
          type: integer
          description: 플레이 리스트 넘버
          format: int64
          example: 1
        title:
          type: string
          description: 제목
          example: http://dfdfjiweoif.com
        playlistImage:
          type: string
          description: 플레이리스트 이미지 URL
          example: http://dfdfjiweoif.com
        timestamp:
          type: string
          description: 플레이리스트 생성 시간
          format: date
          example: 2024-12-12
        emotion:
          type: string
          description: 감정
          example: SAD
          enum:
          - HAPPY
          - SAD
          - MAD
          - EXCITING
          - TIRED
    UserLoginRequest:
      required:
      - email
      - password
      type: object
      properties:
        email:
          type: string
          description: 이메일
          example: moodipie@gmail.com
        password:
          type: string
          description: password
          example: teamproject1!
    UserLoginResponse:
      type: object
      properties:
        message:
          type: string
          description: 메세지
          example: 회원가입이 완료되었습니다.
        token:
          type: string
          description: 토큰
          example: asdjasdiaojsdasdjaisd2132i438rdhi2d393
    ApiResTrackResponse:
      title: API 응답
      type: object
      properties:
        httpStatus:
          type: integer
          description: 응답코드
          format: int32
        data:
          $ref: "#/components/schemas/TrackResponse"
        message:
          type: string
          description: 응답 메세지
          example: ex.조회에 성공했습니다.
        divisionCode:
          type: string
          description: 오류 구분 코드
          example: 오류시 출력
        errors:
          type: array
          description: 상세 필드 에러
          example: 오류시 출력
          items:
            $ref: "#/components/schemas/FieldErrors"
    TrackResponse:
      type: object
      properties:
        playlistTrackNumber:
          type: integer
          format: int64
        trackId:
          type: string
          description: 트랙 ID
          example: sdakfjiosdwn1dnfsd
        trackName:
          type: string
          description: 트랙 제목
          example: 바다의 왕자
        artistName:
          type: string
          description: 가수이름
          example: 박명수
        imageUrl:
          type: string
          description: 이미지 URL
          example: http://dfdfjiweoif.com
    ApiResListPlaylistResponse:
      title: API 응답
      type: object
      properties:
        httpStatus:
          type: integer
          description: 응답코드
          format: int32
        data:
          type: array
          description: 응답 데이터
          items:
            $ref: "#/components/schemas/PlaylistResponse"
        message:
          type: string
          description: 응답 메세지
          example: ex.조회에 성공했습니다.
        divisionCode:
          type: string
          description: 오류 구분 코드
          example: 오류시 출력
        errors:
          type: array
          description: 상세 필드 에러
          example: 오류시 출력
          items:
            $ref: "#/components/schemas/FieldErrors"
    ApiResPlaylistTrackResponse:
      title: API 응답
      type: object
      properties:
        httpStatus:
          type: integer
          description: 응답코드
          format: int32
        data:
          $ref: "#/components/schemas/PlaylistTrackResponse"
        message:
          type: string
          description: 응답 메세지
          example: ex.조회에 성공했습니다.
        divisionCode:
          type: string
          description: 오류 구분 코드
          example: 오류시 출력
        errors:
          type: array
          description: 상세 필드 에러
          example: 오류시 출력
          items:
            $ref: "#/components/schemas/FieldErrors"
    PlaylistTrackResponse:
      type: object
      properties:
        playlist:
          $ref: "#/components/schemas/PlaylistResponse"
        track:
          type: array
          description: 플레이리스트 트랙 정보
          example:
          - playlistTrackNumber: "1"
            trackId: sdakfjiosdwn1dnfsd
            trackName: 바다의 왕자
            artistName: 박명수
            imageUrl: http://dfdfjiweoif.com
          - playlistTrackNumber: "2"
            trackId: 다른 아이디
            trackName: 다른노래
            artistName: 다른 가수
            imageUrl: 다른 링크
          items:
            $ref: "#/components/schemas/TrackResponse"
    ApiResPlaylistTrackEachResponse:
      title: API 응답
      type: object
      properties:
        httpStatus:
          type: integer
          description: 응답코드
          format: int32
        data:
          $ref: "#/components/schemas/PlaylistTrackEachResponse"
        message:
          type: string
          description: 응답 메세지
          example: ex.조회에 성공했습니다.
        divisionCode:
          type: string
          description: 오류 구분 코드
          example: 오류시 출력
        errors:
          type: array
          description: 상세 필드 에러
          example: 오류시 출력
          items:
            $ref: "#/components/schemas/FieldErrors"
    PlaylistTrackEachResponse:
      type: object
      properties:
        playlistTrackNumber:
          type: integer
          description: 플리 속 트랙 번호
          format: int64
          example: 1
        trackId:
          type: string
          description: 트랙 ID
          example: sdakfjiosdwn1dnfsd
        trackName:
          type: string
          description: 트랙 제목
          example: 바다의 왕자
        artistName:
          type: string
          description: 가수이름
          example: 박명수
        imageUrl:
          type: string
          description: 이미지 URL
          example: http://dfdfjiweoif.com
